name: barcodeokapi
description: Okapi's ass is a barcode!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS デザイン
  cupertino_icons:
  # immutable な model作成用
  freezed_annotation:
  # 状態管理パッケージ
  flutter_riverpod:
  json_annotation:

  riverpod:
  riverpod_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  # ビルドランナー, freezed 等の監視に使用
  build_runner:
  build_verify:
  # immutable な model 作成用
  freezed:
  json_serializable:
  riverpod_generator:

  # custom_lint: ^0.3.2

flutter:
  uses-material-design: true

