name: barcodeokapi
description: Okapi's ass is a barcode!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+3

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # 画像圧縮の為
  flutter_image_compress: ^1.1.3
  # 状態管理の為
  flutter_riverpod:
  # immutable な 状態を作成する為
  freezed_annotation: ^2.2.0
  # 状態管理の為, 未利用なので後で消す
  hooks_riverpod:
  # アルバムやカメラアプリを利用する為
  # TODO: バージョンは要確認
  # `image_picker ライブラリは、Android SDK のバージョンによっては動作しない可能性があります。しかし、 compilesdkversion を 30 のままにして image_picker を使用することはできます。以下はその方法です。
  #
  # image_picker のバージョンを更新する
  # まず、image_picker のバージョンを最新に更新することをお勧めします。これにより、最新の Android SDK バージョンで動作するようにライブラリが更新されます。以下のように pubspec.yaml ファイルを更新してください。
  # image_picker: 0.7.0

  # json ←→ Object の from, to を楽にする為
  json_annotation: ^4.8.0
  # # 未利用なので後で消す
  # riverpod:
  # # 未利用なので後で消す
  # riverpod_annotation:

dev_dependencies:
  # freezed や json_serialized は build_runner で 自動生成ファイル作る為
  build_runner: ^2.3.3
  # build_verify: ^3.0.0
  # custom_lint: ^0.3.2
  # アプリアイコン追加の為
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  # immutable な 状態を作成する為
  freezed: ^2.3.2
  # json ←→ Object の from, to を楽にする為
  json_serializable: ^6.6.1
  # # 未利用
  riverpod_generator:
  # # riverpod_lint:

flutter:
  uses-material-design: true

# アイコン設定
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/icon.png'
