name: barcodeokapi
description: Okapi's ass is a barcode!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation: ^2.2.0
  hooks_riverpod:
  json_annotation: ^4.8.0
  riverpod:
  riverpod_annotation:

dev_dependencies:
  build_runner: ^2.3.3
  # build_verify: ^3.0.0
  # custom_lint: ^0.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator:
  # riverpod_lint:

flutter:
  uses-material-design: true

